apply plugin: 'com.android.library'

android {
    compileSdkVersion 37

    defaultConfig {
        minSdkVersion 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions 'env'

    productFlavors {
        dev {
            dimension 'env'
        }
        prod {
            dimension 'env'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    namespace = 'com.ebomike.ebologger'
    testOptions {
        targetSdk 37
    }
    lint {
        targetSdk 37
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation(libs.androidx.espresso.core) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    implementation libs.androidx.appcompat
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.mockito.core
    androidTestImplementation libs.dexmaker
    androidTestImplementation libs.dexmaker.mockito
}
